import { test, expect, type Page } from '@playwright/test'
import type { AxiosInstance } from 'axios'
import type { Profile } from '../src/contracts/profile'
import type { Wallet } from '../src/contracts/wallet'

async function control<T = unknown>(page: Page, method: string, url: string, data?: unknown): Promise<T> {
  return page.evaluate(async (input) => {
    const path = '/src/api/client.ts'
    const module = await import(path) as { createApiClient: (options: { baseURL: string; timeoutMs: number }) => AxiosInstance }
    return (await module.createApiClient({ baseURL: '/api', timeoutMs: 10000 }).request(input)).data as T
  }, { method, url, data })
}
const profileForm = (page: Page) => page.getByRole('form', { name: 'Dados pessoais' })
const passwordForm = (page: Page) => page.getByRole('form', { name: 'Alterar senha', exact: true })
const walletForm = (page: Page) => page.getByRole('form', { name: /^(Adicionar|Editar) carteira$/ })
const nav = (page: Page) => page.getByRole('navigation', { name: 'Navegação da conta' })
const address = (digit: string) => '0x' + digit.repeat(40)
const image = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jA3sAAAAASUVORK5CYII=', 'base64')
async function login(page: Page, email = 'collector@example.com', password = 'Jungle123!') {
  const dialog = page.getByRole('dialog', { name: 'Entrar', exact: true })
  await dialog.getByLabel(/^E-mail/).fill(email)
  await dialog.getByLabel(/^Senha/).fill(password)
  await dialog.getByRole('button', { name: 'Entrar', exact: true }).click()
}
async function open(page: Page, route = 'profile') {
  await control(page, 'POST', '/auth/login', { email: 'collector@example.com', password: 'Jungle123!' })
  await page.goto('/account/' + route)
  await expect(nav(page)).toBeVisible()
  if (route === 'profile') await expect(profileForm(page).getByLabel('Nome de exibição')).toHaveValue('Alex Collector')
  else await expect(page.getByRole('article', { name: 'Carteira principal', exact: true })).toBeVisible()
}
async function logout(page: Page) {
  if ((page.viewportSize()?.width ?? 0) < 1024) await page.getByRole('button', { name: 'Abrir menu' }).click()
  await page.getByRole('button', { name: 'Sair', exact: true }).filter({ visible: true }).click()
  await expect(page.getByRole('dialog', { name: 'Entrar', exact: true })).toBeVisible()
}
async function fillPassword(page: Page, current = 'Jungle123!', next = 'AccountNew123!') {
  const form = passwordForm(page)
  await form.getByLabel(/^Senha atual/).fill(current)
  await form.getByLabel(/^Nova senha/).fill(next)
  await form.getByLabel(/^Confirmar nova senha/).fill(next)
}
async function select(page: Page, label: string, option: string) {
  await walletForm(page).getByRole('combobox', { name: label, exact: true }).click()
  await page.getByRole('option', { name: option, exact: true }).click()
}
async function newWallet(page: Page, label = 'Reserva Polygon', value = address('a')) {
  await page.getByRole('button', { name: 'Adicionar carteira', exact: true }).click()
  await walletForm(page).getByLabel(/^Nome da carteira/).fill(label)
  await walletForm(page).getByLabel(/^Endereço da carteira/).fill(value)
}
test.beforeEach(async ({ page }) => {
  const initial = page.waitForResponse((res) => new URL(res.url()).pathname === '/api/auth/session')
  await page.goto('/design-system')
  await (await initial).finished()
  await expect(page.getByRole('heading', { name: 'Design System', exact: true })).toBeVisible()
  await control(page, 'POST', '/__mock/reset', { scenario: 'default', latencyMs: 0, now: '2026-09-12T12:00:00.000Z' })
})

for (const route of ['profile', 'wallets']) {
  test(route + ' is protected and login returns to the requested account route', async ({ page }) => {
    await page.goto('/account/' + route)
    await expect(page.getByRole('dialog', { name: 'Entrar', exact: true })).toBeVisible()
    expect(new URL(page.url()).searchParams.get('redirect')).toBe('/account/' + route)
    await login(page)
    await expect(nav(page)).toBeVisible()
    await expect(nav(page).getByRole('link', { name: route === 'profile' ? 'Dados do perfil' : 'Carteiras' })).toHaveAttribute('aria-current', 'page')
  })
}
test('profile uses one HTTP query, saves personal data, synchronizes session and survives refresh', async ({ page }) => {
  let reads = 0
  page.on('request', (req) => { if (req.method() === 'GET' && new URL(req.url()).pathname === '/api/profile') reads++ })
  await open(page)
  expect(reads).toBe(1)
  await expect(profileForm(page).getByRole('button', { name: 'Salvar perfil' })).toBeDisabled()
  await profileForm(page).getByLabel('Nome de exibição').fill('Alex Atualizado')
  await profileForm(page).getByLabel('E-mail').fill('alex.updated@example.com')
  await profileForm(page).getByLabel('Sobre você').fill('Colecionador de arte digital.')
  await profileForm(page).getByRole('button', { name: 'Salvar perfil' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Perfil atualizado.' })).toBeVisible()
  const session = await control<{ user: { name: string } }>(page, 'GET', '/auth/session')
  expect(session.user.name).toBe('Alex Atualizado')
  if ((page.viewportSize()?.width ?? 0) >= 1024) await expect(page.getByRole('banner').getByRole('link', { name: 'Alex Atualizado' })).toBeVisible()
  await page.reload()
  await expect(profileForm(page).getByLabel('Nome de exibição')).toHaveValue('Alex Atualizado')
  await expect(profileForm(page).getByLabel('Sobre você')).toHaveValue('Colecionador de arte digital.')
})
test('profile validation and email conflict remain associated with their fields', async ({ page }) => {
  await open(page)
  const form = profileForm(page)
  await form.getByLabel('Nome de exibição').fill('A')
  await form.getByRole('button', { name: 'Salvar perfil' }).click()
  await expect(form.getByLabel('Nome de exibição')).toHaveAttribute('aria-invalid', 'true')
  await expect(form.getByLabel('Nome de exibição')).toBeFocused()
  await form.getByLabel('Nome de exibição').fill('Alex Collector')
  await form.getByLabel('E-mail').fill('second@example.com')
  await form.getByRole('button', { name: 'Salvar perfil' }).click()
  await expect(form.getByLabel('E-mail')).toHaveAccessibleDescription('Erro: Este e-mail já está cadastrado.')
  await expect(form.getByLabel('E-mail')).toBeFocused()
  expect((await control<Profile>(page, 'GET', '/profile')).email).toBe('collector@example.com')
})
for (const route of ['profile', 'wallets']) {
  test(route + ' GET failure is local to its page and recovers with retry', async ({ page }) => {
    await open(page, route === 'profile' ? 'wallets' : 'profile')
    await control(page, 'PATCH', '/__mock/scenario', { scenario: 'server-error' })
    await nav(page).getByRole('link', { name: route === 'profile' ? 'Dados do perfil' : 'Carteiras' }).click()
    await expect(page.getByRole('heading', { name: route === 'profile' ? 'Não foi possível carregar o perfil' : 'Não foi possível carregar as carteiras' })).toBeVisible()
    await expect(nav(page)).toBeVisible()
    await control(page, 'PATCH', '/__mock/scenario', { scenario: 'default' })
    await page.getByRole('button', { name: 'Tentar novamente', exact: true }).click()
    if (route === 'profile') await expect(profileForm(page).getByLabel('Nome de exibição')).toHaveValue('Alex Collector')
    else await expect(page.getByRole('article', { name: 'Carteira principal', exact: true })).toBeVisible()
  })
}
test('profile update server error preserves the draft and supports retry', async ({ page }) => {
  await open(page)
  await profileForm(page).getByLabel('Nome de exibição').fill('Nome preservado')
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'server-error' })
  await profileForm(page).getByRole('button', { name: 'Salvar perfil' }).click()
  await expect(profileForm(page).getByRole('alert')).toBeVisible()
  await expect(profileForm(page).getByLabel('Nome de exibição')).toHaveValue('Nome preservado')
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'default' })
  await profileForm(page).getByRole('button', { name: 'Salvar perfil' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Perfil atualizado.' })).toBeVisible()
})
test('avatar preview is unsaved until HTTP confirmation and persists after reload', async ({ page }) => {
  await open(page)
  await page.getByLabel(/^Escolher imagem/).setInputFiles({ name: 'avatar.png', mimeType: 'image/png', buffer: image })
  await expect(page.getByRole('img', { name: 'Prévia do novo avatar, ainda não salvo' })).toBeVisible()
  expect((await control<Profile>(page, 'GET', '/profile')).avatarUrl).toBeNull()
  await page.getByRole('button', { name: 'Salvar avatar', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Avatar atualizado.' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('img', { name: 'Avatar de Alex Collector', exact: true })).toBeVisible()
  expect((await control<Profile>(page, 'GET', '/profile')).avatarUrl).toMatch(/^data:image\/png;base64,/)
})
test('invalid avatar and avatar server failure do not replace the confirmed image', async ({ page }) => {
  await open(page)
  const input = page.getByLabel(/^Escolher imagem/)
  await input.setInputFiles({ name: 'note.txt', mimeType: 'text/plain', buffer: Buffer.from('invalid') })
  await expect(input).toHaveAttribute('aria-invalid', 'true')
  await expect(page.getByRole('button', { name: 'Salvar avatar' })).toBeDisabled()
  await input.setInputFiles({ name: 'avatar.png', mimeType: 'image/png', buffer: image })
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'server-error' })
  await page.getByRole('button', { name: 'Salvar avatar' }).click()
  await expect(input).toHaveAttribute('aria-invalid', 'true')
  await expect(page.getByRole('img', { name: 'Prévia do novo avatar, ainda não salvo' })).toBeVisible()
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'default' })
  expect((await control<Profile>(page, 'GET', '/profile')).avatarUrl).toBeNull()
})
test('password update clears fields and old password fails while the new password logs in', async ({ page }) => {
  await open(page)
  await fillPassword(page)
  await passwordForm(page).getByRole('button', { name: 'Alterar senha', exact: true }).click()
  await expect(passwordForm(page).getByRole('status')).toContainText('Senha alterada.')
  await expect(passwordForm(page).getByLabel(/^Nova senha/)).toHaveValue('')
  expect(await page.evaluate(() => JSON.stringify({ ...localStorage, ...sessionStorage }))).not.toContain('AccountNew123!')
  await logout(page)
  await login(page)
  await expect(page.getByRole('alert')).toContainText('E-mail ou senha inválidos')
  await login(page, 'collector@example.com', 'AccountNew123!')
  await expect(profileForm(page).getByLabel('Nome de exibição')).toHaveValue('Alex Collector')
})
test('password validation and wrong current password show accessible errors without expiring session', async ({ page }) => {
  await open(page)
  await fillPassword(page, 'Wrong123!', 'short')
  await passwordForm(page).getByRole('button', { name: 'Alterar senha', exact: true }).click()
  await expect(passwordForm(page).getByLabel(/^Nova senha/)).toHaveAttribute('aria-invalid', 'true')
  await fillPassword(page, 'Wrong123!')
  await passwordForm(page).getByLabel(/^Confirmar nova senha/).fill('Mismatch123!')
  await passwordForm(page).getByRole('button', { name: 'Alterar senha', exact: true }).click()
  await expect(passwordForm(page).getByLabel(/^Confirmar nova senha/)).toHaveAttribute('aria-invalid', 'true')
  await fillPassword(page, 'Wrong123!')
  await passwordForm(page).getByRole('button', { name: 'Alterar senha', exact: true }).click()
  await expect(passwordForm(page).getByLabel(/^Senha atual/)).toHaveAccessibleDescription('Erro: A senha atual não confere.')
  await expect(passwordForm(page).getByLabel(/^Senha atual/)).toBeFocused()
  await expect(nav(page)).toBeVisible()
})
test('new account has an empty wallet list with a working inline add form', async ({ page }) => {
  await control(page, 'POST', '/auth/register', { name: 'New Collector', email: 'new@example.com', password: 'Jungle123!' })
  await page.goto('/account/wallets')
  await expect(page.getByRole('heading', { name: 'Você ainda não tem carteiras' })).toBeVisible()
  await newWallet(page, 'Minha primeira')
  await expect(walletForm(page).getByRole('combobox', { name: 'Função da carteira' })).toContainText('Principal')
  await walletForm(page).getByRole('button', { name: 'Salvar carteira' }).click()
  await expect(page.getByRole('article', { name: 'Minha primeira' })).toBeVisible()
})
test('wallet creation and editing use HTTP and persist on refresh', async ({ page }) => {
  await open(page, 'wallets')
  await newWallet(page)
  await select(page, 'Rede', 'Polygon')
  await walletForm(page).getByRole('button', { name: 'Salvar carteira' }).click()
  const card = page.getByRole('article', { name: 'Reserva Polygon' })
  await expect(card).toContainText('Secundária')
  await expect(card).toContainText('Polygon')
  await card.getByRole('button', { name: 'Editar Reserva Polygon' }).click()
  await walletForm(page).getByLabel('Nome da carteira').fill('Reserva atualizada')
  await walletForm(page).getByLabel('Endereço da carteira').fill(address('b'))
  await walletForm(page).getByRole('button', { name: 'Salvar carteira' }).click()
  await expect(page.getByRole('article', { name: 'Reserva atualizada' })).toContainText(address('b'))
  await page.reload()
  await expect(page.getByRole('article', { name: 'Reserva atualizada' })).toContainText(address('b'))
})
test('wallet role change respects one primary and one secondary and rejects an occupied role', async ({ page }) => {
  await open(page, 'wallets')
  await page.getByRole('button', { name: 'Editar Carteira principal' }).click()
  await select(page, 'Função da carteira', 'Secundária')
  await walletForm(page).getByRole('button', { name: 'Salvar carteira' }).click()
  await expect(page.getByRole('region', { name: 'Carteira secundária', exact: true })).toContainText(address('1'))
  await newWallet(page, 'Principal nova')
  await walletForm(page).getByRole('button', { name: 'Salvar carteira' }).click()
  await expect(page.getByRole('region', { name: 'Carteira principal', exact: true })).toContainText('Principal nova')
  await page.getByRole('button', { name: 'Editar Carteira principal' }).click()
  await select(page, 'Função da carteira', 'Principal')
  await walletForm(page).getByRole('button', { name: 'Salvar carteira' }).click()
  await expect(walletForm(page).getByRole('combobox', { name: 'Função da carteira' })).toHaveAttribute('aria-invalid', 'true')
  const wallets = await control<Wallet[]>(page, 'GET', '/wallets')
  expect(wallets.filter((wallet) => wallet.role === 'primary')).toHaveLength(1)
  expect(wallets.filter((wallet) => wallet.role === 'secondary')).toHaveLength(1)
})
test('wallet validation and duplicate address conflicts are associated with fields', async ({ page }) => {
  await open(page, 'wallets')
  await newWallet(page, 'X', 'bad')
  await walletForm(page).getByRole('button', { name: 'Salvar carteira' }).click()
  await expect(walletForm(page).getByLabel('Nome da carteira')).toHaveAttribute('aria-invalid', 'true')
  await walletForm(page).getByLabel('Nome da carteira').fill('Duplicada')
  await walletForm(page).getByLabel('Endereço da carteira').fill(address('1'))
  await walletForm(page).getByRole('button', { name: 'Salvar carteira' }).click()
  await expect(walletForm(page).getByLabel('Endereço da carteira')).toHaveAccessibleDescription('0x seguido de 40 caracteres hexadecimais. Erro: Esta carteira já está cadastrada.')
  await expect(walletForm(page).getByLabel('Endereço da carteira')).toBeFocused()
})
test('wallet server failure keeps the draft and confirmed list until successful retry', async ({ page }) => {
  await open(page, 'wallets')
  await newWallet(page)
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'server-error' })
  await walletForm(page).getByRole('button', { name: 'Salvar carteira' }).click()
  await expect(walletForm(page).getByRole('alert')).toBeVisible()
  await expect(page.getByRole('article', { name: 'Reserva Polygon' })).toHaveCount(0)
  await expect(walletForm(page).getByLabel('Nome da carteira')).toHaveValue('Reserva Polygon')
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'default' })
  await walletForm(page).getByRole('button', { name: 'Salvar carteira' }).click()
  await expect(page.getByRole('article', { name: 'Reserva Polygon' })).toBeVisible()
})
test('expired profile request uses existing login flow and returns to profile', async ({ page }) => {
  await open(page)
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'session-expired' })
  await control(page, 'POST', '/__mock/clock/advance', { milliseconds: 1001 })
  await profileForm(page).getByLabel('Nome de exibição').fill('Expirado')
  await profileForm(page).getByRole('button', { name: 'Salvar perfil' }).click()
  await expect(page.getByRole('dialog', { name: 'Entrar', exact: true })).toBeVisible()
  expect(new URL(page.url()).searchParams.get('redirect')).toBe('/account/profile')
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'default' })
  await login(page)
  await expect(profileForm(page).getByLabel('Nome de exibição')).toHaveValue('Alex Collector')
})
test('logout and user switch never reveal the previous profile or wallets', async ({ page }) => {
  await open(page)
  await profileForm(page).getByLabel('Sobre você').fill('Private A biography')
  await profileForm(page).getByRole('button', { name: 'Salvar perfil' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Perfil atualizado.' })).toBeVisible()
  await nav(page).getByRole('link', { name: 'Carteiras' }).click()
  await newWallet(page, 'Private A wallet')
  await walletForm(page).getByRole('button', { name: 'Salvar carteira' }).click()
  await expect(page.getByRole('article', { name: 'Private A wallet' })).toBeVisible()
  await logout(page)
  await login(page, 'second@example.com')
  await expect(page.getByRole('article', { name: 'Carteira principal', exact: true })).toContainText(address('2'))
  await expect(page.getByText('Private A wallet', { exact: true })).toHaveCount(0)
  await nav(page).getByRole('link', { name: 'Dados do perfil' }).click()
  await expect(profileForm(page).getByLabel('Nome de exibição')).toHaveValue('Sam Collector')
  await expect(profileForm(page).getByLabel('Sobre você')).toHaveValue('')
})
test('slow profile and wallet pages show independent skeletons', async ({ page }) => {
  await open(page, 'wallets')
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'slow-network', latencyMs: null })
  await nav(page).getByRole('link', { name: 'Dados do perfil' }).click()
  await expect(page.getByRole('status', { name: 'Carregando perfil', exact: true })).toBeVisible()
  await expect(profileForm(page)).toBeVisible()
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'default' })
})
test('pending profile save prevents duplicate submissions', async ({ page }) => {
  await open(page)
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'slow-network', latencyMs: null })
  let writes = 0
  page.on('request', (req) => { if (req.method() === 'PATCH' && new URL(req.url()).pathname === '/api/profile') writes++ })
  await profileForm(page).getByLabel('Nome de exibição').fill('Pending profile')
  await profileForm(page).getByRole('button', { name: 'Salvar perfil' }).click()
  await expect(profileForm(page).getByRole('button', { name: 'Salvando perfil…' })).toBeDisabled()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('status').filter({ hasText: 'Perfil atualizado.' })).toBeVisible()
  expect(writes).toBe(1)
})
test('late profile save cannot restore the previous identity after logout', async ({ page }) => {
  await open(page)
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'slow-network', latencyMs: 1800 })
  await profileForm(page).getByLabel('Nome de exibição').fill('Late private A')
  await profileForm(page).getByRole('button', { name: 'Salvar perfil' }).click()
  await logout(page)
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'default', latencyMs: 0 })
  await login(page, 'second@example.com')
  await expect(profileForm(page).getByLabel('Nome de exibição')).toHaveValue('Sam Collector')
  await expect(page.getByText('Late private A', { exact: true })).toHaveCount(0)
})
test('account layout and inline forms support keyboard and responsive widths', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await open(page)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('profile.png'), fullPage: true, animations: 'disabled' })
  const toggle = passwordForm(page).getByRole('button', { name: 'Mostrar senha atual' })
  await toggle.focus()
  await page.keyboard.press('Space')
  await expect(passwordForm(page).getByLabel(/^Senha atual/)).toHaveAttribute('type', 'text')
  await nav(page).getByRole('link', { name: 'Carteiras' }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('article', { name: 'Carteira principal', exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath('wallets.png'), fullPage: true, animations: 'disabled' })
  await newWallet(page)
  await walletForm(page).getByLabel('Nome da carteira').focus()
  await page.keyboard.press('Tab')
  await expect(walletForm(page).getByRole('combobox', { name: 'Rede', exact: true })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(walletForm(page).getByLabel('Nome da carteira')).toBeFocused()
  await page.screenshot({ path: info.outputPath('wallet-form.png'), fullPage: true, animations: 'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await expect(walletForm(page)).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Minhas carteiras' })).toBeFocused()
  expect(errors).toEqual([])
})

test('wallet loading remains local to account navigation', async ({ page }) => {
  await open(page)
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'slow-network', latencyMs: null })
  await nav(page).getByRole('link', { name: 'Carteiras' }).click()
  await expect(page.getByRole('status', { name: 'Carregando carteiras', exact: true })).toBeVisible()
  await expect(nav(page)).toBeVisible()
  await expect(page.getByRole('article', { name: 'Carteira principal', exact: true })).toBeVisible()
})
test('password server error clears secrets and permits resubmission', async ({ page }) => {
  await open(page)
  await fillPassword(page)
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'server-error' })
  await passwordForm(page).getByRole('button', { name: 'Alterar senha', exact: true }).click()
  await expect(passwordForm(page).getByRole('alert')).toBeVisible()
  await expect(passwordForm(page).getByLabel(/^Senha atual/)).toHaveValue('')
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'default' })
  await fillPassword(page)
  await passwordForm(page).getByRole('button', { name: 'Alterar senha', exact: true }).click()
  await expect(passwordForm(page).getByRole('status')).toContainText('Senha alterada.')
})
test('wallet pending save sends once and expired wallet update returns to login', async ({ page }) => {
  await open(page, 'wallets')
  await newWallet(page)
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'slow-network', latencyMs: null })
  let writes = 0
  page.on('request', (req) => { if (req.method() === 'POST' && new URL(req.url()).pathname === '/api/wallets') writes++ })
  await walletForm(page).getByRole('button', { name: 'Salvar carteira' }).click()
  await expect(walletForm(page).getByRole('button', { name: 'Salvando carteira…' })).toBeDisabled()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('article', { name: 'Reserva Polygon' })).toBeVisible()
  expect(writes).toBe(1)
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'session-expired', latencyMs: 0 })
  await control(page, 'POST', '/__mock/clock/advance', { milliseconds: 1001 })
  await page.getByRole('button', { name: 'Editar Reserva Polygon' }).click()
  await walletForm(page).getByLabel('Nome da carteira').fill('Expired wallet')
  await walletForm(page).getByRole('button', { name: 'Salvar carteira' }).click()
  await expect(page.getByRole('dialog', { name: 'Entrar', exact: true })).toBeVisible()
  expect(new URL(page.url()).searchParams.get('redirect')).toBe('/account/wallets')
})
