import { test, expect, type Page } from '@playwright/test'
import type { AxiosInstance } from 'axios'
import type { Order } from '../src/contracts/order'
async function control<T = unknown>(page: Page, method: string, url: string, data?: unknown): Promise<T> {
  return page.evaluate(async (input) => {
    const path = '/src/api/client.ts'
    const module = await import(path) as { createApiClient: (options: { baseURL: string; timeoutMs: number }) => AxiosInstance }
    return (await module.createApiClient({ baseURL: '/api', timeoutMs: 10000 }).request(input)).data as T
  }, { method, url, data })
}
const form = (page: Page) => page.getByRole('form', { name: 'Finalizar compra', exact: true })
const confirm = (page: Page) => form(page).getByRole('button', { name: 'Confirmar compra', exact: true })
async function openCheckout(page: Page, scenario = 'default') {
  await control(page, 'POST', '/auth/login', { email: 'collector@example.com', password: 'Jungle123!' })
  await control(page, 'PATCH', '/__mock/scenario', { scenario, latencyMs: 0 })
  await page.goto('/checkout')
  await expect(form(page).getByTestId('order-total')).toHaveText('1.195 ETH')
}
async function connect(page: Page, decision = 'Autorizar conexão') {
  await page.getByRole('button', { name: 'Conectar carteira', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Conectar carteira', exact: true })
  await dialog.getByRole('button', { name: decision, exact: true }).click()
  await expect(dialog).toHaveCount(0)
}
async function create(page: Page) {
  const response = page.waitForResponse((res) => new URL(res.url()).pathname === '/api/orders' && res.request().method() === 'POST' && res.ok())
  await confirm(page).click()
  return await (await response).json() as Order
}
test.beforeEach(async ({ page }) => {
  const initial = page.waitForResponse((res) => new URL(res.url()).pathname === '/api/auth/session')
  await page.goto('/design-system')
  await (await initial).finished()
  await expect(page.getByRole('heading', { name: 'Design System', exact: true })).toBeVisible()
  await control(page, 'POST', '/__mock/reset', { scenario: 'default', latencyMs: 0, now: '2026-09-12T12:00:00.000Z' })
})
test('empty checkout and missing wallet have real recovery actions', async ({ page }) => {
  await control(page, 'POST', '/auth/register', { name: 'New User', email: 'checkout@example.com', password: 'Jungle123!' })
  await page.goto('/checkout')
  await expect(page.getByRole('heading', { name: 'Seu carrinho está vazio' })).toBeVisible()
  await control(page, 'POST', '/cart/items', { nftId: 'nft-001', editionId: 'standard', quantity: 1 })
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Cadastre uma carteira para continuar' })).toBeVisible()
  await page.getByRole('link', { name: 'Adicionar carteira', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Minhas carteiras' })).toBeVisible()
})
test('wallet connection supports declined, connected and disconnected states', async ({ page }) => {
  await openCheckout(page)
  await expect(confirm(page)).toBeDisabled()
  await connect(page, 'Recusar conexão')
  await expect(page.getByRole('status').filter({ hasText: 'Conexão recusada.' })).toBeVisible()
  await expect(confirm(page)).toBeDisabled()
  await connect(page)
  await expect(confirm(page)).toBeEnabled()
  await page.getByRole('button', { name: 'Desconectar carteira' }).click()
  await expect(confirm(page)).toBeDisabled()
})
test('confirmed purchase uses a snapshot, resumes directly and removes only purchased quantities', async ({ page }) => {
  await openCheckout(page, 'payment-confirmed')
  await connect(page)
  const order = await create(page)
  await expect(page.getByRole('heading', { name: 'Pagamento em processamento' })).toBeVisible()
  await control(page, 'POST', '/cart/items', { nftId: 'nft-001', editionId: 'standard', quantity: 2 })
  await control(page, 'PATCH', '/__mock/nfts/nft-001', { priceEth: '1.4' })
  await control(page, 'POST', '/__mock/clock/advance', { milliseconds: 3000 })
  await expect(page.getByRole('heading', { name: 'Pedido confirmado' })).toBeVisible({ timeout: 10000 })
  await expect(page.getByTestId('order-total')).toHaveText('1.195 ETH')
  await expect(page.getByText('SIMULATED-' + order.id, { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Pedido confirmado' })).toBeVisible()
  await expect(page.getByTestId('order-total')).toHaveText('1.195 ETH')
  const cart = await control<{ items: { quantity: number }[] }>(page, 'GET', '/cart')
  expect(cart.items[0]?.quantity).toBe(2)
})
test('declined payment preserves cart and never presents a receipt', async ({ page }) => {
  await openCheckout(page, 'payment-declined')
  await connect(page)
  await create(page)
  await control(page, 'POST', '/__mock/clock/advance', { milliseconds: 3000 })
  await expect(page.getByRole('heading', { name: 'Pagamento recusado' })).toBeVisible({ timeout: 10000 })
  await expect(page.getByRole('heading', { name: 'Recibo da compra' })).toHaveCount(0)
  const cart = await control<{ items: { quantity: number }[] }>(page, 'GET', '/cart')
  expect(cart.items[0]?.quantity).toBe(1)
})
test('price revalidation changes the summary but requires another confirmation before creating', async ({ page }) => {
  await openCheckout(page, 'price-changed')
  await connect(page)
  let posts = 0
  page.on('request', (req) => { if (req.method() === 'POST' && new URL(req.url()).pathname === '/api/orders') posts++ })
  await confirm(page).click()
  await expect(page.getByRole('status').filter({ hasText: 'Revise o resumo e confirme novamente.' })).toBeVisible()
  await expect(form(page).getByTestId('order-total')).toHaveText('1.295 ETH')
  expect(posts).toBe(0)
  await create(page)
  expect(posts).toBe(1)
})
test('sold out revalidation blocks creation and preserves the cart for review', async ({ page }) => {
  await openCheckout(page, 'sold-out')
  await connect(page)
  await confirm(page).click()
  await expect(page.getByRole('heading', { name: 'Cotação indisponível' })).toBeVisible()
  await expect(confirm(page)).toBeDisabled()
  const state = await control<{ counts: { orders: number } }>(page, 'GET', '/__mock/state')
  expect(state.counts.orders).toBe(0)
  const cart = await control<{ items: unknown[] }>(page, 'GET', '/cart')
  expect(cart.items).toHaveLength(1)
})
test('timeout recovery after reload reuses the exact key and payload and returns one order', async ({ page }) => {
  test.setTimeout(45000)
  await openCheckout(page, 'order-timeout')
  await connect(page)
  const attempts: { key: string | undefined; body: string | null }[] = []
  page.on('request', (req) => { if (req.method() === 'POST' && new URL(req.url()).pathname === '/api/orders') attempts.push({ key: req.headers()['idempotency-key'], body: req.postData() }) })
  await confirm(page).click()
  await expect(page.getByRole('button', { name: 'Recuperar pedido', exact: true })).toBeEnabled({ timeout: 18000 })
  await page.reload()
  await page.getByRole('button', { name: 'Recuperar pedido', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Pagamento em processamento' })).toBeVisible()
  expect(attempts).toHaveLength(2)
  expect(attempts[0]?.key).toBeTruthy()
  expect(attempts[1]).toEqual(attempts[0])
  const state = await control<{ counts: { orders: number } }>(page, 'GET', '/__mock/state')
  expect(state.counts.orders).toBe(1)
})
test('double submission produces one order and collector validation is accessible', async ({ page }) => {
  await openCheckout(page)
  await connect(page)
  await form(page).getByLabel(/^Nome de exibição/).fill('A')
  await confirm(page).click()
  await expect(form(page).getByLabel(/^Nome de exibição/)).toHaveAttribute('aria-invalid', 'true')
  await form(page).getByLabel(/^Nome de exibição/).fill('Alex Collector')
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'slow-network', latencyMs: null })
  let posts = 0
  page.on('request', (req) => { if (req.method() === 'POST' && new URL(req.url()).pathname === '/api/orders') posts++ })
  await confirm(page).click()
  await expect(page.getByRole('button', { name: 'Revalidando e enviando…' })).toBeDisabled()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Pagamento em processamento' })).toBeVisible({ timeout: 10000 })
  expect(posts).toBe(1)
})
test('order routes enforce user ownership and never expose another account snapshot', async ({ page }) => {
  await openCheckout(page)
  await connect(page)
  const order = await create(page)
  await control(page, 'POST', '/auth/logout')
  await control(page, 'POST', '/auth/login', { email: 'second@example.com', password: 'Jungle123!' })
  await page.goto('/orders/' + order.id)
  await expect(page.getByRole('heading', { name: 'Pedido não encontrado' })).toBeVisible()
  await expect(page.getByText(order.snapshot.walletAddress, { exact: true })).toHaveCount(0)
})
test('checkout expired session returns to login and requires a fresh connection and quote', async ({ page }) => {
  await openCheckout(page)
  await connect(page)
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'session-expired' })
  await control(page, 'POST', '/__mock/clock/advance', { milliseconds: 1001 })
  await confirm(page).click()
  const dialog = page.getByRole('dialog', { name: 'Entrar', exact: true })
  await expect(dialog).toBeVisible()
  expect(new URL(page.url()).searchParams.get('redirect')).toBe('/checkout')
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'default' })
  await dialog.getByLabel(/^E-mail/).fill('collector@example.com')
  await dialog.getByLabel(/^Senha/).fill('Jungle123!')
  await dialog.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(form(page).getByTestId('order-total')).toHaveText('1.195 ETH')
  await expect(confirm(page)).toBeDisabled()
})
test('checkout layout and connection dialog support keyboard and responsive widths', async ({ page }, info) => {
  await openCheckout(page)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('checkout.png'), fullPage: true, animations: 'disabled' })
  const trigger = page.getByRole('button', { name: 'Conectar carteira', exact: true })
  await trigger.focus()
  await page.keyboard.press('Enter')
  const dialog = page.getByRole('dialog', { name: 'Conectar carteira', exact: true })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: 'Autorizar conexão' }).focus()
  await page.keyboard.press('Tab')
  await expect(dialog.getByRole('button', { name: 'Recusar conexão' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await connect(page)
  await confirm(page).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Pagamento em processamento' })).toBeVisible()
})
