import { test, expect } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/design-system')
  // The dev-only lazy route compiles its primitives on the first Vite request.
  await expect(page.getByRole('heading', { name: 'Design System', exact: true })).toBeVisible({ timeout: 15000 })
})

test('responsive primitives render without overflow and fields expose their descriptions', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  const name = page.getByRole('textbox', { name: 'Nome de exibição' })
  await expect(name).toHaveAccessibleDescription('Como seu nome será apresentado.')
  await expect(name).toHaveAttribute('required', '')
  const email = page.getByRole('textbox', { name: 'E-mail de exemplo' })
  await expect(email).toHaveAttribute('aria-invalid', 'true')
  await expect(email).toHaveAccessibleDescription('Erro: Informe um e-mail válido.')
  await expect(page.getByRole('textbox', { name: 'Campo indisponível' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Indisponível', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Carregando', exact: true })).toHaveAttribute('aria-busy', 'true')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  const inputBox = await name.boundingBox()
  expect(inputBox?.height).toBeGreaterThanOrEqual(44)
  await page.screenshot({ animations: 'disabled', path: testInfo.outputPath('design-system.png'), fullPage: true })
  await page.getByRole('region', { name: 'Cards de apresentação' }).screenshot({ animations: 'disabled', path: testInfo.outputPath('cards.png') })
  expect(errors).toEqual([])
})

test('Select, Checkbox and RadioGroup support keyboard interaction and disabled options', async ({ page }) => {
  const select = page.getByRole('combobox', { name: 'Rede de exemplo' })
  await select.focus()
  await page.keyboard.press('Space')
  await expect(page.getByRole('listbox')).toBeVisible()
  await expect(page.getByRole('option', { name: 'Ethereum', exact: true })).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('option', { name: 'Polygon', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(select).toContainText('Polygon')
  await expect(select).toBeFocused()
  await page.keyboard.press('Tab')
  const checkbox = page.getByRole('checkbox', { name: 'Receber novidades (exemplo)' })
  await expect(checkbox).toBeFocused()
  await page.keyboard.press('Space')
  await expect(checkbox).toBeChecked()
  await expect(page.getByRole('checkbox', { name: 'Opção indisponível', exact: true })).toBeDisabled()
  await page.keyboard.press('Tab')
  const first = page.getByRole('radio', { name: 'Primeira opção', exact: true })
  await expect(first).toBeFocused()
  // Radix defers roving focus; keep keydown active until selection follows focus.
  await page.keyboard.down('ArrowDown')
  await expect(page.getByRole('radio', { name: 'Segunda opção' })).toBeChecked()
  await page.keyboard.up('ArrowDown')
  await page.keyboard.down('ArrowDown')
  await expect(first).toBeChecked()
  await page.keyboard.up('ArrowDown')
  await page.keyboard.press('Shift+Tab')
  await expect(checkbox).toBeFocused()
})

test('Dialog and Sheet trap focus, close with Escape and restore their trigger', async ({ page }, testInfo) => {
  const trigger = page.getByRole('button', { name: 'Abrir diálogo', exact: true })
  await trigger.focus()
  await page.keyboard.press('Enter')
  const dialog = page.getByRole('dialog', { name: 'Exemplo de diálogo' })
  await expect(dialog).toBeVisible()
  const input = page.getByRole('textbox', { name: 'Campo do diálogo' })
  await expect(input).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('button', { name: 'Fechar diálogo' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(input).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Concluir exemplo' })).toBeFocused()
  await page.keyboard.press('Tab')
  await page.keyboard.press('Tab')
  await expect(input).toBeFocused()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ animations: 'disabled', path: testInfo.outputPath('dialog.png') })
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
  await expect(trigger).toBeFocused()
  await page.keyboard.press('Tab')
  const panelTrigger = page.getByRole('button', { name: 'Abrir painel', exact: true })
  await expect(panelTrigger).toBeFocused()
  await page.keyboard.press('Space')
  const panel = page.getByRole('dialog', { name: 'Exemplo de painel' })
  await expect(panel).toBeVisible()
  const checkbox = page.getByRole('checkbox', { name: 'Opção do painel' })
  await expect(checkbox).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('button', { name: 'Fechar painel' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(checkbox).toBeFocused()
  await page.keyboard.press('Space')
  await expect(checkbox).toBeChecked()
  await page.screenshot({ animations: 'disabled', path: testInfo.outputPath('sheet.png') })
  await page.keyboard.press('Escape')
  await expect(panelTrigger).toBeFocused()
})

test('quantity limits and favorite controls remain independent from card navigation', async ({ page }) => {
  const minus = page.getByRole('button', { name: 'Diminuir quantidade de exemplo' })
  const plus = page.getByRole('button', { name: 'Aumentar quantidade de exemplo' })
  await expect(minus).toBeDisabled()
  await plus.focus()
  await page.keyboard.press('Enter')
  await page.keyboard.press('Space')
  await expect(plus).toBeDisabled()
  await expect(page.getByRole('group', { name: 'Quantidade de exemplo' })).toContainText('3')
  await minus.click()
  await expect(plus).toBeEnabled()
  const favorite = page.getByRole('button', { name: 'Favoritar Obra de exemplo #042' })
  await favorite.focus()
  await page.keyboard.press('Space')
  await expect(favorite).toHaveAttribute('aria-pressed', 'true')
  await expect(page).toHaveURL(/design-system$/)
  expect(await favorite.evaluate((element) => element.closest('a'))).toBeNull()
  const cardLink = page.getByRole('link').filter({ has: page.getByRole('heading', { name: 'Obra de exemplo #042' }) })
  await cardLink.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Uma nova coleção começa aqui.' })).toBeVisible()
})

test('skeletons preserve square media, expose loading and honor reduced motion', async ({ page }) => {
  await expect(page.getByRole('status', { name: 'Carregando NFTs', exact: true })).toBeVisible()
  const card = page.getByRole('status', { name: 'Carregando NFT', exact: true }).first()
  const media = await card.locator('[data-slot="skeleton"]').first().boundingBox()
  expect(Math.abs((media?.width ?? 0) - (media?.height ?? 0))).toBeLessThan(1)
  const skeleton = page.locator('[data-slot="skeleton"]').first()
  expect(await skeleton.evaluate((element) => getComputedStyle(element, '::after').animationName)).toBe('shimmer')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  expect(await skeleton.evaluate((element) => getComputedStyle(element, '::after').animationName)).toBe('none')
  const grid = page.getByRole('tab', { name: 'Grade', exact: true })
  await grid.focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('status', { name: 'Carregando detalhes do NFT' })).toBeVisible()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('status', { name: 'Carregando resumo' })).toBeVisible()
})

test('core text, input boundaries and keyboard focus have adequate contrast', async ({ page }) => {
  const results = await page.evaluate(() => {
    const style = getComputedStyle(document.documentElement)
    const luminance = (token: string) => {
      const hex = style.getPropertyValue(token).trim().slice(1)
      const rgb = [0, 2, 4].map((offset) => parseInt(hex.slice(offset, offset + 2), 16) / 255)
        .map((value) => value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4)
      return rgb.reduce((sum, value, index) => sum + value * ([0.2126, 0.7152, 0.0722][index] ?? 0), 0)
    }
    return [
      ['--foreground', '--background', 4.5], ['--muted-foreground', '--card', 4.5],
      ['--primary', '--card', 4.5], ['--primary-foreground', '--primary', 4.5],
      ['--destructive', '--card', 4.5], ['--input', '--background', 3],
      ['--input', '--card', 3], ['--ring', '--card', 3],
    ].map(([front, back, minimum]) => {
      const a = luminance(String(front)); const b = luminance(String(back))
      return { front, back, minimum, ratio: (Math.max(a, b) + 0.05) / (Math.min(a, b) + 0.05) }
    })
  })
  for (const result of results) expect(result.ratio, String(result.front)).toBeGreaterThanOrEqual(Number(result.minimum))
  const input = page.getByRole('textbox', { name: 'Nome de exibição' })
  await input.focus()
  await page.keyboard.press('Tab')
  const email = page.getByRole('textbox', { name: 'E-mail de exemplo' })
  await expect(email).toBeFocused()
  expect(await email.evaluate((element) => getComputedStyle(element).outlineStyle)).toBe('solid')
})
