import { test, expect, type Page } from '@playwright/test'
async function api(page: Page, path: string, data?: unknown, method = 'POST') {
  return page.evaluate(async ({ path, data, method }) => {
    const response = await fetch('/api' + path, { method, credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: data === undefined ? undefined : JSON.stringify(data) })
    return response.status === 204 ? null : response.json()
  }, { path, data, method })
}
const favorite = (page: Page) => page.getByRole('button', { name: /(?:Favoritar|Remover favorito) Golden Ape #001/ })
test.beforeEach(async ({ page }) => {
  await page.goto('/design-system')
  await expect(page.getByRole('heading', { name: 'Design System', exact: true })).toBeVisible()
  await api(page, '/__mock/reset', { latencyMs: 0 })
})
test('visitor favorites requires login and preserves detail return context', async ({ page }) => {
  await page.goto('/nfts/nft-001')
  await favorite(page).click()
  await expect(page.getByRole('dialog', { name: 'Entrar', exact: true })).toBeVisible()
  expect(new URL(page.url()).searchParams.get('redirect')).toContain('/nfts/nft-001')
})
test('optimistic favorite changes before response, persists and is isolated between users', async ({ page }) => {
  await api(page, '/auth/login', { email: 'collector@example.com', password: 'Jungle123!' })
  await page.goto('/nfts/nft-001')
  await expect(favorite(page)).toHaveAttribute('aria-pressed', 'true')
  await api(page, '/__mock/scenario', { scenario: 'default', latencyMs: 1200 }, 'PATCH')
  let completed = false
  page.on('response', (response) => { if (response.request().method() === 'DELETE' && response.url().endsWith('/favorites/nft-001')) completed = true })
  await favorite(page).click()
  await expect(favorite(page)).toHaveAttribute('aria-pressed', 'false')
  expect(completed).toBe(false)
  await expect(favorite(page)).toBeEnabled()
  await page.reload()
  await expect(favorite(page)).toHaveAttribute('aria-pressed', 'false')
  await favorite(page).click()
  await expect(favorite(page)).toBeEnabled()
  await api(page, '/auth/logout')
  await api(page, '/auth/login', { email: 'second@example.com', password: 'Jungle123!' })
  await page.reload()
  await expect(favorite(page)).toHaveAttribute('aria-pressed', 'false')
})
test('failed favorite mutation rolls back and allows retry', async ({ page }) => {
  await api(page, '/auth/login', { email: 'collector@example.com', password: 'Jungle123!' })
  await page.goto('/nfts/nft-001')
  await expect(favorite(page)).toHaveAttribute('aria-pressed', 'true')
  await api(page, '/__mock/scenario', { scenario: 'server-error', latencyMs: 800 }, 'PATCH')
  await favorite(page).click()
  await expect(favorite(page)).toHaveAttribute('aria-pressed', 'false')
  await expect(page.getByRole('alert').filter({ hasText: 'O estado anterior foi restaurado' })).toBeVisible()
  await expect(favorite(page)).toHaveAttribute('aria-pressed', 'true')
  await api(page, '/__mock/scenario', { scenario: 'default', latencyMs: 0 }, 'PATCH')
  await page.reload()
  await favorite(page).click()
  await expect(favorite(page)).toHaveAttribute('aria-pressed', 'false')
  await expect(favorite(page)).toBeEnabled()
})
