import { test, expect, type Page } from '@playwright/test'
import type { AxiosInstance } from 'axios'
import type { Cart } from '../src/contracts/cart'
import type { NFT } from '../src/contracts/nft'

async function control<T = unknown>(page: Page, method: string, url: string, data?: unknown): Promise<T> {
  return page.evaluate(async (input) => {
    const modulePath = '/src/api/client.ts'
    const module = await import(modulePath) as { createApiClient: (options: { baseURL: string; timeoutMs: number }) => AxiosInstance }
    const api = module.createApiClient({ baseURL: '/api', timeoutMs: 10000 })
    return (await api.request({ method: input.method, url: input.url, data: input.data })).data as T
  }, { method, url, data })
}
const title = (page: Page, name = 'Golden Ape #001') => page.getByRole('heading', { level: 1, name })
const purchase = (page: Page) => page.getByRole('region', { name: 'Informações e aquisição' })
const quantity = (page: Page) => purchase(page).getByRole('group', { name: 'Quantidade de NFTs' }).locator('output')
const plus = (page: Page) => page.getByRole('button', { name: 'Aumentar quantidade de NFTs' })
const minus = (page: Page) => page.getByRole('button', { name: 'Diminuir quantidade de NFTs' })
const add = (page: Page) => page.getByRole('button', { name: 'Adicionar ao carrinho', exact: true })
const related = (page: Page) => page.getByRole('list', { name: 'NFTs relacionados' })

test.beforeEach(async ({ page }) => {
  const initialSession = page.waitForResponse((res) => new URL(res.url()).pathname === '/api/auth/session')
  await page.goto('/design-system')
  await (await initialSession).finished()
  await expect(page.getByRole('heading', { name: 'Design System', exact: true })).toBeVisible({ timeout: 15000 })
  await control(page, 'POST', '/__mock/reset', { scenario: 'default', latencyMs: 0, now: '2026-09-10T12:00:00.000Z' })
})

test('direct detail and refresh render authoritative HTTP data without visiting Home', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  const response = page.waitForResponse((res) => new URL(res.url()).pathname === '/api/nfts/nft-001' && res.ok())
  await page.goto('/nfts/nft-001')
  const nft = await (await response).json() as NFT
  await expect(title(page, nft.name)).toBeVisible()
  await expect(page.getByTestId('nft-unit-price')).toHaveText('1.19 ETH')
  await expect(purchase(page)).toContainText(nft.description)
  await expect(page.getByRole('radio', { name: 'Standard', exact: true })).toBeChecked()
  await expect(page.getByRole('radio', { name: 'Limited · Esgotada', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Favoritar · em breve' })).toBeDisabled()
  await expect(add(page)).toBeEnabled()
  const media = page.getByRole('region', { name: 'Galeria do NFT' }).getByRole('img')
  await expect(media).toHaveAttribute('src', nft.imageUrl)
  await expect(media).toHaveAttribute('alt', nft.name)
  await expect.poll(() => media.evaluate((img) => (img as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
  const bounds = await media.boundingBox()
  expect(Math.abs((bounds?.width ?? 0) - (bounds?.height ?? 0))).toBeLessThan(1)
  await expect(related(page).getByRole('article')).toHaveCount(5)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await page.getByTestId('nft-detail-content').evaluate((el) => getComputedStyle(el).gridTemplateColumns.split(' ').length)).toBe((page.viewportSize()?.width ?? 0) >= 768 ? 2 : 1)
  await page.screenshot({ path: testInfo.outputPath('detail.png'), fullPage: true, animations: 'disabled' })
  await page.getByTestId('nft-detail-content').screenshot({ path: testInfo.outputPath('detail-content.png'), animations: 'disabled' })
  await page.reload()
  await expect(title(page)).toBeVisible()
  await expect(add(page)).toBeEnabled()
  expect(errors).toEqual([])
})

test('missing resource is a distinct 404 with catalog return and no purchase', async ({ page }) => {
  const response = page.waitForResponse((res) => new URL(res.url()).pathname === '/api/nfts/does-not-exist')
  await page.goto('/nfts/does-not-exist?q=owl&sort=name&page=1')
  expect((await response).status()).toBe(404)
  await expect(title(page, 'NFT não encontrado')).toBeVisible()
  await expect(add(page)).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Tentar novamente' })).toHaveCount(0)
  await page.getByRole('link', { name: 'Voltar ao catálogo' }).click()
  await expect(page.getByRole('searchbox', { name: 'Buscar NFTs' })).toHaveValue('owl')
  await expect(page.getByRole('combobox', { name: 'Ordenar por' })).toContainText('Nome A–Z')
})

test('slow-network displays detail skeleton before the real data', async ({ page }) => {
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'slow-network', latencyMs: 2000 })
  await page.goto('/nfts/nft-001')
  await expect(page.getByRole('status', { name: 'Carregando detalhes do NFT' })).toBeVisible()
  await expect(title(page)).toBeVisible()
  await expect(page.getByRole('status', { name: 'Carregando detalhes do NFT' })).toHaveCount(0)
})

for (const scenario of ['network-error', 'server-error']) {
  test(`${scenario} has accessible error feedback and working retry`, async ({ page }) => {
    await control(page, 'PATCH', '/__mock/scenario', { scenario })
    await page.goto('/nfts/nft-001')
    await expect(title(page, 'Não foi possível carregar o NFT')).toBeVisible({ timeout: 10000 })
    await expect(page.getByRole('alert')).toBeVisible()
    await control(page, 'PATCH', '/__mock/scenario', { scenario: 'default', latencyMs: 0 })
    await page.getByRole('button', { name: 'Tentar novamente' }).click()
    await expect(title(page)).toBeVisible()
  })
}

test('editions enforce quantity limits and reset quantity when switching', async ({ page }) => {
  await page.goto('/nfts/nft-002')
  await expect(title(page, 'Jungle Panther #002')).toBeVisible()
  await expect(quantity(page)).toHaveText('1')
  await expect(minus(page)).toBeDisabled()
  for (let i = 1; i < 9; i++) await plus(page).click()
  await expect(quantity(page)).toHaveText('9')
  await expect(plus(page)).toBeDisabled()
  await page.getByRole('radio', { name: 'Limited', exact: true }).click()
  await expect(quantity(page)).toHaveText('1')
  await expect(purchase(page)).toContainText('2 unidades disponíveis na edição Limited.')
  await plus(page).click()
  await expect(quantity(page)).toHaveText('2')
  await expect(plus(page)).toBeDisabled()
  await minus(page).click()
  await expect(quantity(page)).toHaveText('1')
  await expect(minus(page)).toBeDisabled()
  await expect(page.getByTestId('nft-unit-price')).toHaveText('0.05 ETH')
})

test('sold-out state disables acquisition and controls without a fake purchase', async ({ page }) => {
  // This scenario normally changes stock during quotation; its existing control prepares the same persisted state for a direct detail visit.
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'sold-out' })
  await control(page, 'PATCH', '/__mock/nfts/nft-001', { availableQuantity: 0 })
  await page.goto('/nfts/nft-001')
  await expect(title(page)).toBeVisible()
  await expect(purchase(page).getByRole('status').filter({ hasText: 'NFT esgotado' })).toHaveText('NFT esgotado. Nenhuma edição disponível.')
  await expect(page.getByRole('button', { name: 'Edição esgotada' })).toBeDisabled()
  await expect(plus(page)).toBeDisabled()
  await expect(minus(page)).toBeDisabled()
  await expect(page.getByRole('radio', { name: 'Standard · Esgotada' })).toBeDisabled()
  const cart = await control<Cart>(page, 'GET', '/cart')
  expect(cart.items).toHaveLength(0)
})

test('price and stock refetch preserve content, clamp quantity and handle background failure', async ({ page }) => {
  await page.goto('/nfts/nft-002')
  await expect(title(page, 'Jungle Panther #002')).toBeVisible()
  await plus(page).click()
  await plus(page).click()
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'price-changed', latencyMs: 2000 })
  await control(page, 'PATCH', '/__mock/nfts/nft-002', { priceEth: '0.000000000000000001', editionId: 'standard', availableQuantity: 1 })
  await page.getByRole('button', { name: 'Atualizar NFT' }).click()
  await expect(page.getByRole('button', { name: 'Atualizando…' })).toBeDisabled()
  await expect(title(page, 'Jungle Panther #002')).toBeVisible()
  await expect(page.getByRole('status', { name: 'Carregando detalhes do NFT' })).toHaveCount(0)
  await expect(page.getByTestId('nft-unit-price')).toHaveText('0.000000000000000001 ETH')
  await expect(quantity(page)).toHaveText('1')
  await expect(plus(page)).toBeDisabled()
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'server-error', latencyMs: 0 })
  await page.getByRole('button', { name: 'Atualizar NFT' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Os dados anteriores continuam visíveis' })).toBeVisible({ timeout: 10000 })
  await expect(title(page, 'Jungle Panther #002')).toBeVisible()
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'default' })
  await page.getByRole('status').filter({ hasText: 'Os dados anteriores continuam visíveis' }).getByRole('button', { name: 'Tentar novamente' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Os dados anteriores continuam visíveis' })).toHaveCount(0)
})

test('related NFTs use the collection API, exclude the current NFT and navigate with URL state', async ({ page }) => {
  const response = page.waitForResponse((res) => {
    const url = new URL(res.url())
    return url.pathname === '/api/nfts' && url.searchParams.get('collection') === 'golden'
  })
  await page.goto('/nfts/nft-029?q=ape&sort=price-asc&page=2')
  await response
  await expect(related(page).getByRole('article')).toHaveCount(5)
  await expect(related(page).getByRole('heading', { name: 'Golden Ape #029' })).toHaveCount(0)
  await related(page).getByRole('link').first().click()
  await expect(title(page, 'Golden Ape #025')).toBeVisible()
  expect(new URL(page.url()).searchParams.get('q')).toBe('ape')
  expect(new URL(page.url()).searchParams.get('page')).toBe('2')
  await page.getByRole('link', { name: 'Voltar ao catálogo' }).click()
  await expect(page.getByRole('searchbox', { name: 'Buscar NFTs' })).toHaveValue('ape')
  await expect(page.getByRole('combobox', { name: 'Ordenar por' })).toContainText('Menor preço')
})

test('guest add-to-cart waits for HTTP confirmation and survives refresh', async ({ page }) => {
  await page.goto('/nfts/nft-002')
  await expect(title(page, 'Jungle Panther #002')).toBeVisible()
  await page.getByRole('radio', { name: 'Limited', exact: true }).click()
  await plus(page).click()
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'slow-network', latencyMs: 1500 })
  const response = page.waitForResponse((res) => new URL(res.url()).pathname === '/api/cart/items' && res.request().method() === 'POST')
  await add(page).click()
  await expect(page.getByRole('button', { name: 'Adicionando…' })).toBeDisabled()
  await expect(plus(page)).toBeDisabled()
  const result = await response
  expect(result.status()).toBe(201)
  expect(result.request().postDataJSON()).toEqual({ nftId: 'nft-002', editionId: 'limited', quantity: 2 })
  await expect(purchase(page).getByRole('status').filter({ hasText: 'adicionada(s) ao carrinho' })).toBeVisible()
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'default', latencyMs: 0 })
  await page.reload()
  await expect(title(page, 'Jungle Panther #002')).toBeVisible()
  const cart = await control<Cart>(page, 'GET', '/cart')
  expect(cart.owner.kind).toBe('guest')
  expect(cart.items).toHaveLength(1)
  expect(cart.items[0]).toMatchObject({ nftId: 'nft-002', editionId: 'limited', quantity: 2 })
})

test('server rejects stale stock and the detail reconciles without reporting success', async ({ page }) => {
  await page.goto('/nfts/nft-001')
  await expect(title(page)).toBeVisible()
  await control(page, 'PATCH', '/__mock/nfts/nft-001', { availableQuantity: 0 })
  await add(page).click()
  await expect(purchase(page).getByRole('alert')).toContainText('Estoque insuficiente')
  await expect(page.getByRole('button', { name: 'Edição esgotada' })).toBeDisabled()
  await expect(purchase(page)).not.toContainText('adicionada(s) ao carrinho')
  expect((await control<Cart>(page, 'GET', '/cart')).items).toHaveLength(0)
})

test('failed cart mutation has accessible feedback and can be explicitly retried', async ({ page }) => {
  await page.goto('/nfts/nft-001')
  await expect(title(page)).toBeVisible()
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'server-error' })
  await add(page).click()
  await expect(purchase(page).getByRole('alert')).toContainText('Serviço temporariamente indisponível')
  await expect(purchase(page)).not.toContainText('adicionada(s) ao carrinho')
  await control(page, 'PATCH', '/__mock/scenario', { scenario: 'default' })
  await add(page).click()
  await expect(purchase(page).getByRole('status').filter({ hasText: 'adicionada(s) ao carrinho' })).toBeVisible()
  expect((await control<Cart>(page, 'GET', '/cart')).items[0]?.quantity).toBe(1)
})

test('keyboard operates editions, quantity, tabs, related links and acquisition', async ({ page }) => {
  await page.goto('/nfts/nft-002')
  await expect(title(page, 'Jungle Panther #002')).toBeVisible()
  const standard = page.getByRole('radio', { name: 'Standard', exact: true })
  const limited = page.getByRole('radio', { name: 'Limited', exact: true })
  await standard.focus()
  await page.keyboard.down('ArrowRight')
  await expect(limited).toBeChecked()
  await page.keyboard.up('ArrowRight')
  await page.keyboard.press('Tab')
  await expect(plus(page)).toBeFocused()
  await page.keyboard.press('Space')
  await expect(quantity(page)).toHaveText('2')
  await minus(page).focus()
  await page.keyboard.press('Enter')
  await expect(quantity(page)).toHaveText('1')
  const description = page.getByRole('tab', { name: 'Detalhes do NFT' })
  const information = page.getByRole('tab', { name: 'Informações', exact: true })
  await description.focus()
  await page.keyboard.press('ArrowRight')
  await expect(information).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('tabpanel')).toContainText('Disponibilidade total')
  await page.keyboard.press('ArrowLeft')
  await expect(description).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('tabpanel')).toContainText('Colecionável fictício')
  await add(page).focus()
  await page.keyboard.press('Shift+Tab')
  await expect(plus(page)).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(add(page)).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(purchase(page).getByRole('status').filter({ hasText: 'adicionada(s) ao carrinho' })).toBeVisible()
  await related(page).getByRole('link').first().focus()
  await page.keyboard.press('Enter')
  await expect(title(page, 'Jungle Panther #030')).toBeVisible()
})
